"""
Viibe - Scout Identity Service

Scouts are the sensor network — not power users, not a feature.
Every user in the system has a role relative to the data hierarchy:

  SENSOR (Scout)     — generates signal. The hardware layer.
  CONSUMER           — reads signal generated by scouts.
  OPERATOR (Merchant)— owns a venue node in the network.
  CONTROLLER (Admin) — manages network integrity.

This module is the authoritative source for:
  - What tier a user occupies (newbie → regular → scout → elite)
  - What capabilities their tier unlocks
  - What their contribution means to network signal quality
  - Which onboarding path the frontend should route them to

Designed so the frontend never needs to make role decisions itself —
it asks for the identity context and acts on what it receives.
"""
from datetime import datetime, timedelta, timezone
from app.config import db


# ── Tier thresholds ───────────────────────────────────────────────────────────

SCOUT_TIERS = {
    "newbie": {
        "label":         "Scout Trainee",
        "min_ratings":   0,
        "max_ratings":   9,
        "credibility":   0.15,
        "role":          "consumer",           # primarily reads data
        "onboarding":    "scout_intro",        # show scout orientation
        "capabilities":  ["rate", "read_scores", "lobby"],
        "signal_weight": "minimal",
        "description":   "Learning the network. Every tap counts.",
    },
    "regular": {
        "label":         "Scout",
        "min_ratings":   10,
        "max_ratings":   29,
        "credibility":   0.48,
        "role":          "sensor",             # contributing signal
        "onboarding":    "scout_active",
        "capabilities":  ["rate", "read_scores", "lobby", "crew", "dna", "streaks"],
        "signal_weight": "moderate",
        "description":   "Active sensor in the network. Your signal matters.",
    },
    "scout": {
        "label":         "Verified Scout",
        "min_ratings":   30,
        "max_ratings":   99,
        "credibility":   1.0,
        "role":          "sensor",
        "onboarding":    "scout_verified",
        "capabilities":  ["rate", "read_scores", "lobby", "crew", "dna", "streaks",
                          "oracle_access", "consensus_weight"],
        "signal_weight": "full",
        "description":   "Full network sensor. Oracle-level signal weight.",
    },
    "elite": {
        "label":         "Elite Scout",
        "min_ratings":   100,
        "max_ratings":   None,
        "credibility":   1.0,
        "role":          "anchor_sensor",      # highest trust, anchors aggregates
        "onboarding":    "scout_elite",
        "capabilities":  ["rate", "read_scores", "lobby", "crew", "dna", "streaks",
                          "oracle_access", "consensus_weight", "icon_eligible",
                          "leaderboard_anchor", "vibe_dna_influence"],
        "signal_weight": "full",
        "description":   "Anchor node. Your ratings shape how others see the city.",
    },
}


def _compute_tier(total_ratings: int) -> str:
    """Derive tier from total lifetime ratings."""
    if total_ratings >= 100:
        return "elite"
    if total_ratings >= 30:
        return "scout"
    if total_ratings >= 10:
        return "regular"
    return "newbie"


async def get_scout_identity(user: dict) -> dict:
    """
    Return the full identity context for a user.

    Called on login, signup, and profile refresh.
    The frontend uses `onboarding` to route to the correct flow,
    and `capabilities` to gate features without hardcoding tier logic.
    """
    total_ratings = user.get("total_ratings", 0)
    tier = _compute_tier(total_ratings)
    tier_meta = SCOUT_TIERS[tier]

    # Network contribution stats
    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=7)
    ratings_7d = await db.ratings.count_documents({
        "user_id": user["id"],
        "timestamp": {"$gte": week_ago},
    })

    # Venues this scout has contributed signal to (lifetime)
    venues_rated = await db.ratings.distinct("venue_id", {"user_id": user["id"]})

    # Next tier progress
    next_tier = None
    ratings_to_next = None
    if tier != "elite":
        tier_order = ["newbie", "regular", "scout", "elite"]
        next_tier_key = tier_order[tier_order.index(tier) + 1]
        next_tier_meta = SCOUT_TIERS[next_tier_key]
        ratings_to_next = next_tier_meta["min_ratings"] - total_ratings
        next_tier = next_tier_key

    # Merchant / admin overrides to the role
    role = tier_meta["role"]
    if user.get("is_merchant"):
        role = "operator"
    if user.get("is_admin") or user.get("is_super_admin"):
        role = "controller"

    return {
        "tier":            tier,
        "tier_label":      tier_meta["label"],
        "role":            role,
        "onboarding":      tier_meta["onboarding"],
        "capabilities":    tier_meta["capabilities"],
        "signal_weight":   tier_meta["signal_weight"],
        "credibility":     tier_meta["credibility"],
        "description":     tier_meta["description"],
        # ── Contribution stats ────────────────────────────────────────
        "total_ratings":   total_ratings,
        "ratings_7d":      ratings_7d,
        "venues_contributed": len(venues_rated),
        # ── Progression ───────────────────────────────────────────────
        "next_tier":         next_tier,
        "ratings_to_next":   ratings_to_next,
        # ── Subscription ─────────────────────────────────────────────
        "is_vibe_plus":    user.get("is_vibe_plus", False),
        "icon_tier":       user.get("icon_tier"),
    }
